[package]
name = "graph-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
plotly = { version = "0.10.0", features = ["kaleido"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
